# Default values for workshop-example.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  # container repository
  repository: eu.gcr.io/k8s-workshop-2/app
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

environment: {}
  # CODE: cranky-hippo
  # WORKSHOP_USERNAME: k8s-workshop

secret: {}
  # password: k8s-workshop-password

healthchecks:
  livenessPath: '/live'
  readinessPath: '/ready'

podAnnotations: {}
  # workshop: k8s-workshop-episode-2
  # code: cranky-hippo

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: $CODE.k8s.3fs.si
      paths:
        - /
  tls:
    - secretName: k8s.3fs.si-certificate
      hosts:
        - $CODE.k8s.3fs.si

persistence:
  ## If persistence is enabled, uploaded files will be persisted.
  enabled: false
  ## The path the volume will be mounted at.
  mountPath: /uploadfiles

  ## The subdirectory of the volume to mount to, useful in dev environments
  ## and one PV for multiple services.
  ##
  subPath: ""

  # storageClass: "-"
  accessModes:
    - ReadWriteOnce
  size: 2Gi
  annotations: {}

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 100m
    memory: 64Mi
  requests:
    cpu: 10m
    memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
