{{- $releasename := .Release.Name -}}
{{- if gt (len .Values.secret) 0 -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $releasename | lower }}-secret
  labels:
    app: {{ template "workshop-example.name" . }}
    chart: {{ template "workshop-example.chart" . }}
    release: {{ $releasename }}
data:
{{- range $key, $val := .Values.secret }}
  {{ $key }}: {{ $val | b64enc | quote }}
{{- end }}
{{ end }}
