---
# Default pod resource requests and limits if container does not specify its
# own CPU and Memory limits.
apiVersion: v1
kind: LimitRange
metadata:
  name: workshop-limit-range
spec:
  limits:
    - default:
        memory: 100Mi
        cpu: 50m
      defaultRequest:
        cpu: 50m
        memory: 100Mi
      type: Container
