---
# Total amount of memory and CPU that can be used by all containers running in a
# namespace.
apiVersion: v1
kind: ResourceQuota
metadata:
  name: workshop-resource-quota
spec:
  hard:
    requests.cpu: 500m
    requests.memory: 1Gi
    limits.cpu: 500m
    limits.memory: 1Gi
    pods: "10"
